-- Generated by GenCmds.hs. DO NOT EDIT.

{-# LANGUAGE OverloadedStrings #-}

module Database.Redis.Commands (

-- ** Connection
auth, -- |Authenticate to the server (<http://redis.io/commands/auth>).
echo, -- |Echo the given string (<http://redis.io/commands/echo>).
ping, -- |Ping the server (<http://redis.io/commands/ping>).
quit, -- |Close the connection (<http://redis.io/commands/quit>).
select, -- |Change the selected database for the current connection (<http://redis.io/commands/select>).

-- ** Keys
del, -- |Delete a key (<http://redis.io/commands/del>).
exists, -- |Determine if a key exists (<http://redis.io/commands/exists>).
expire, -- |Set a key's time to live in seconds (<http://redis.io/commands/expire>).
expireat, -- |Set the expiration for a key as a UNIX timestamp (<http://redis.io/commands/expireat>).
keys, -- |Find all keys matching the given pattern (<http://redis.io/commands/keys>).
move, -- |Move a key to another database (<http://redis.io/commands/move>).
objectRefcount, -- |Inspect the internals of Redis objects (<http://redis.io/commands/object>). The Redis command @OBJECT@ is split up into 'objectRefcount', 'objectEncoding', 'objectIdletime'.
objectEncoding, -- |Inspect the internals of Redis objects (<http://redis.io/commands/object>). The Redis command @OBJECT@ is split up into 'objectRefcount', 'objectEncoding', 'objectIdletime'.
objectIdletime, -- |Inspect the internals of Redis objects (<http://redis.io/commands/object>). The Redis command @OBJECT@ is split up into 'objectRefcount', 'objectEncoding', 'objectIdletime'.
persist, -- |Remove the expiration from a key (<http://redis.io/commands/persist>).
randomkey, -- |Return a random key from the keyspace (<http://redis.io/commands/randomkey>).
rename, -- |Rename a key (<http://redis.io/commands/rename>).
renamenx, -- |Rename a key, only if the new key does not exist (<http://redis.io/commands/renamenx>).
ttl, -- |Get the time to live for a key (<http://redis.io/commands/ttl>).
getType, -- |Determine the type stored at key (<http://redis.io/commands/type>).

-- ** Hashes
hdel, -- |Delete one or more hash fields (<http://redis.io/commands/hdel>).
hexists, -- |Determine if a hash field exists (<http://redis.io/commands/hexists>).
hget, -- |Get the value of a hash field (<http://redis.io/commands/hget>).
hgetall, -- |Get all the fields and values in a hash (<http://redis.io/commands/hgetall>).
hincrby, -- |Increment the integer value of a hash field by the given number (<http://redis.io/commands/hincrby>).
hkeys, -- |Get all the fields in a hash (<http://redis.io/commands/hkeys>).
hlen, -- |Get the number of fields in a hash (<http://redis.io/commands/hlen>).
hmget, -- |Get the values of all the given hash fields (<http://redis.io/commands/hmget>).
hmset, -- |Set multiple hash fields to multiple values (<http://redis.io/commands/hmset>).
hset, -- |Set the string value of a hash field (<http://redis.io/commands/hset>).
hsetnx, -- |Set the value of a hash field, only if the field does not exist (<http://redis.io/commands/hsetnx>).
hvals, -- |Get all the values in a hash (<http://redis.io/commands/hvals>).

-- ** Lists
blpop, -- |Remove and get the first element in a list, or block until one is available (<http://redis.io/commands/blpop>).
brpop, -- |Remove and get the last element in a list, or block until one is available (<http://redis.io/commands/brpop>).
brpoplpush, -- |Pop a value from a list, push it to another list and return it; or block until one is available (<http://redis.io/commands/brpoplpush>).
lindex, -- |Get an element from a list by its index (<http://redis.io/commands/lindex>).
linsertBefore, -- |Insert an element before or after another element in a list (<http://redis.io/commands/linsert>). The Redis command @LINSERT@ is split up into 'linsertBefore', 'linsertAfter'.
linsertAfter, -- |Insert an element before or after another element in a list (<http://redis.io/commands/linsert>). The Redis command @LINSERT@ is split up into 'linsertBefore', 'linsertAfter'.
llen, -- |Get the length of a list (<http://redis.io/commands/llen>).
lpop, -- |Remove and get the first element in a list (<http://redis.io/commands/lpop>).
lpush, -- |Prepend one or multiple values to a list (<http://redis.io/commands/lpush>).
lpushx, -- |Prepend a value to a list, only if the list exists (<http://redis.io/commands/lpushx>).
lrange, -- |Get a range of elements from a list (<http://redis.io/commands/lrange>).
lrem, -- |Remove elements from a list (<http://redis.io/commands/lrem>).
lset, -- |Set the value of an element in a list by its index (<http://redis.io/commands/lset>).
ltrim, -- |Trim a list to the specified range (<http://redis.io/commands/ltrim>).
rpop, -- |Remove and get the last element in a list (<http://redis.io/commands/rpop>).
rpoplpush, -- |Remove the last element in a list, append it to another list and return it (<http://redis.io/commands/rpoplpush>).
rpush, -- |Append one or multiple values to a list (<http://redis.io/commands/rpush>).
rpushx, -- |Append a value to a list, only if the list exists (<http://redis.io/commands/rpushx>).

-- ** Server
bgrewriteaof, -- |Asynchronously rewrite the append-only file (<http://redis.io/commands/bgrewriteaof>).
bgsave, -- |Asynchronously save the dataset to disk (<http://redis.io/commands/bgsave>).
configGet, -- |Get the value of a configuration parameter (<http://redis.io/commands/config-get>).
configResetstat, -- |Reset the stats returned by INFO (<http://redis.io/commands/config-resetstat>).
configSet, -- |Set a configuration parameter to the given value (<http://redis.io/commands/config-set>).
dbsize, -- |Return the number of keys in the selected database (<http://redis.io/commands/dbsize>).
flushall, -- |Remove all keys from all databases (<http://redis.io/commands/flushall>).
flushdb, -- |Remove all keys from the current database (<http://redis.io/commands/flushdb>).
info, -- |Get information and statistics about the server (<http://redis.io/commands/info>).
lastsave, -- |Get the UNIX time stamp of the last successful save to disk (<http://redis.io/commands/lastsave>).
save, -- |Synchronously save the dataset to disk (<http://redis.io/commands/save>).
shutdown, -- |Synchronously save the dataset to disk and then shut down the server (<http://redis.io/commands/shutdown>).
slaveof, -- |Make the server a slave of another instance, or promote it as master (<http://redis.io/commands/slaveof>).
slowlogGet, -- |Manages the Redis slow queries log (<http://redis.io/commands/slowlog>). The Redis command @SLOWLOG@ is split up into 'slowlogGet', 'slowlogLen', 'slowlogReset'.
slowlogLen, -- |Manages the Redis slow queries log (<http://redis.io/commands/slowlog>). The Redis command @SLOWLOG@ is split up into 'slowlogGet', 'slowlogLen', 'slowlogReset'.
slowlogReset, -- |Manages the Redis slow queries log (<http://redis.io/commands/slowlog>). The Redis command @SLOWLOG@ is split up into 'slowlogGet', 'slowlogLen', 'slowlogReset'.

-- ** Sets
sadd, -- |Add one or more members to a set (<http://redis.io/commands/sadd>).
scard, -- |Get the number of members in a set (<http://redis.io/commands/scard>).
sdiff, -- |Subtract multiple sets (<http://redis.io/commands/sdiff>).
sdiffstore, -- |Subtract multiple sets and store the resulting set in a key (<http://redis.io/commands/sdiffstore>).
sinter, -- |Intersect multiple sets (<http://redis.io/commands/sinter>).
sinterstore, -- |Intersect multiple sets and store the resulting set in a key (<http://redis.io/commands/sinterstore>).
sismember, -- |Determine if a given value is a member of a set (<http://redis.io/commands/sismember>).
smembers, -- |Get all the members in a set (<http://redis.io/commands/smembers>).
smove, -- |Move a member from one set to another (<http://redis.io/commands/smove>).
spop, -- |Remove and return a random member from a set (<http://redis.io/commands/spop>).
srandmember, -- |Get a random member from a set (<http://redis.io/commands/srandmember>).
srem, -- |Remove one or more members from a set (<http://redis.io/commands/srem>).
sunion, -- |Add multiple sets (<http://redis.io/commands/sunion>).
sunionstore, -- |Add multiple sets and store the resulting set in a key (<http://redis.io/commands/sunionstore>).

-- ** Sorted Sets
zadd, -- |Add one or more members to a sorted set, or update its score if it already exists (<http://redis.io/commands/zadd>).
zcard, -- |Get the number of members in a sorted set (<http://redis.io/commands/zcard>).
zcount, -- |Count the members in a sorted set with scores within the given values (<http://redis.io/commands/zcount>).
zincrby, -- |Increment the score of a member in a sorted set (<http://redis.io/commands/zincrby>).
zrange, -- |Return a range of members in a sorted set, by index (<http://redis.io/commands/zrange>). The Redis command @ZRANGE@ is split up into 'zrange', 'zrangeWithscores'.
zrangeWithscores, -- |Return a range of members in a sorted set, by index (<http://redis.io/commands/zrange>). The Redis command @ZRANGE@ is split up into 'zrange', 'zrangeWithscores'.
zrangebyscore, -- |Return a range of members in a sorted set, by score (<http://redis.io/commands/zrangebyscore>). The Redis command @ZRANGEBYSCORE@ is split up into 'zrangebyscore', 'zrangebyscoreWithscores', 'zrangebyscoreLimit', 'zrangebyscoreWithscoresLimit'.
zrangebyscoreWithscores, -- |Return a range of members in a sorted set, by score (<http://redis.io/commands/zrangebyscore>). The Redis command @ZRANGEBYSCORE@ is split up into 'zrangebyscore', 'zrangebyscoreWithscores', 'zrangebyscoreLimit', 'zrangebyscoreWithscoresLimit'.
zrangebyscoreLimit, -- |Return a range of members in a sorted set, by score (<http://redis.io/commands/zrangebyscore>). The Redis command @ZRANGEBYSCORE@ is split up into 'zrangebyscore', 'zrangebyscoreWithscores', 'zrangebyscoreLimit', 'zrangebyscoreWithscoresLimit'.
zrangebyscoreWithscoresLimit, -- |Return a range of members in a sorted set, by score (<http://redis.io/commands/zrangebyscore>). The Redis command @ZRANGEBYSCORE@ is split up into 'zrangebyscore', 'zrangebyscoreWithscores', 'zrangebyscoreLimit', 'zrangebyscoreWithscoresLimit'.
zrank, -- |Determine the index of a member in a sorted set (<http://redis.io/commands/zrank>).
zrem, -- |Remove one or more members from a sorted set (<http://redis.io/commands/zrem>).
zremrangebyrank, -- |Remove all members in a sorted set within the given indexes (<http://redis.io/commands/zremrangebyrank>).
zremrangebyscore, -- |Remove all members in a sorted set within the given scores (<http://redis.io/commands/zremrangebyscore>).
zrevrange, -- |Return a range of members in a sorted set, by index, with scores ordered from high to low (<http://redis.io/commands/zrevrange>). The Redis command @ZREVRANGE@ is split up into 'zrevrange', 'zrevrangeWithscores'.
zrevrangeWithscores, -- |Return a range of members in a sorted set, by index, with scores ordered from high to low (<http://redis.io/commands/zrevrange>). The Redis command @ZREVRANGE@ is split up into 'zrevrange', 'zrevrangeWithscores'.
zrevrangebyscore, -- |Return a range of members in a sorted set, by score, with scores ordered from high to low (<http://redis.io/commands/zrevrangebyscore>). The Redis command @ZREVRANGEBYSCORE@ is split up into 'zrevrangebyscore', 'zrevrangebyscoreWithscores', 'zrevrangebyscoreLimit', 'zrevrangebyscoreWithscoresLimit'.
zrevrangebyscoreWithscores, -- |Return a range of members in a sorted set, by score, with scores ordered from high to low (<http://redis.io/commands/zrevrangebyscore>). The Redis command @ZREVRANGEBYSCORE@ is split up into 'zrevrangebyscore', 'zrevrangebyscoreWithscores', 'zrevrangebyscoreLimit', 'zrevrangebyscoreWithscoresLimit'.
zrevrangebyscoreLimit, -- |Return a range of members in a sorted set, by score, with scores ordered from high to low (<http://redis.io/commands/zrevrangebyscore>). The Redis command @ZREVRANGEBYSCORE@ is split up into 'zrevrangebyscore', 'zrevrangebyscoreWithscores', 'zrevrangebyscoreLimit', 'zrevrangebyscoreWithscoresLimit'.
zrevrangebyscoreWithscoresLimit, -- |Return a range of members in a sorted set, by score, with scores ordered from high to low (<http://redis.io/commands/zrevrangebyscore>). The Redis command @ZREVRANGEBYSCORE@ is split up into 'zrevrangebyscore', 'zrevrangebyscoreWithscores', 'zrevrangebyscoreLimit', 'zrevrangebyscoreWithscoresLimit'.
zrevrank, -- |Determine the index of a member in a sorted set, with scores ordered from high to low (<http://redis.io/commands/zrevrank>).
zscore, -- |Get the score associated with the given member in a sorted set (<http://redis.io/commands/zscore>).

-- ** Strings
append, -- |Append a value to a key (<http://redis.io/commands/append>).
decr, -- |Decrement the integer value of a key by one (<http://redis.io/commands/decr>).
decrby, -- |Decrement the integer value of a key by the given number (<http://redis.io/commands/decrby>).
get, -- |Get the value of a key (<http://redis.io/commands/get>).
getbit, -- |Returns the bit value at offset in the string value stored at key (<http://redis.io/commands/getbit>).
getrange, -- |Get a substring of the string stored at a key (<http://redis.io/commands/getrange>).
getset, -- |Set the string value of a key and return its old value (<http://redis.io/commands/getset>).
incr, -- |Increment the integer value of a key by one (<http://redis.io/commands/incr>).
incrby, -- |Increment the integer value of a key by the given number (<http://redis.io/commands/incrby>).
mget, -- |Get the values of all the given keys (<http://redis.io/commands/mget>).
mset, -- |Set multiple keys to multiple values (<http://redis.io/commands/mset>).
msetnx, -- |Set multiple keys to multiple values, only if none of the keys exist (<http://redis.io/commands/msetnx>).
set, -- |Set the string value of a key (<http://redis.io/commands/set>).
setbit, -- |Sets or clears the bit at offset in the string value stored at key (<http://redis.io/commands/setbit>).
setex, -- |Set the value and expiration of a key (<http://redis.io/commands/setex>).
setnx, -- |Set the value of a key, only if the key does not exist (<http://redis.io/commands/setnx>).
setrange, -- |Overwrite part of a string at key starting at the specified offset (<http://redis.io/commands/setrange>).
strlen, -- |Get the length of the value stored in a key (<http://redis.io/commands/strlen>).

-- ** Transactions
discard, -- |Discard all commands issued after MULTI (<http://redis.io/commands/discard>).
exec, -- |Execute all commands issued after MULTI (<http://redis.io/commands/exec>).
multi, -- |Mark the start of a transaction block (<http://redis.io/commands/multi>).
unwatch, -- |Forget about all watched keys (<http://redis.io/commands/unwatch>).
watch, -- |Watch the given keys to determine execution of the MULTI/EXEC block (<http://redis.io/commands/watch>).
) where

import Prelude hiding (min,max)
import Database.Redis.ManualCommands
import Database.Redis.Types
import Database.Redis.Internal

flushall :: (RedisResult a)
    => Redis a
flushall  = sendRequest (["FLUSHALL"] )

hdel :: (RedisArg key, RedisArg field, RedisResult a)
    => key -- ^ 
    -> [field] -- ^ 
    -> Redis a
hdel key field = sendRequest (["HDEL"] ++ [encode key] ++ map encode field )

hincrby :: (RedisArg key, RedisArg field, RedisArg increment, RedisResult a)
    => key -- ^ 
    -> field -- ^ 
    -> increment -- ^ 
    -> Redis a
hincrby key field increment = sendRequest (["HINCRBY"] ++ [encode key] ++ [encode field] ++ [encode increment] )

configResetstat :: (RedisResult a)
    => Redis a
configResetstat  = sendRequest (["CONFIG","RESETSTAT"] )

del :: (RedisArg key, RedisResult a)
    => [key] -- ^ 
    -> Redis a
del key = sendRequest (["DEL"] ++ map encode key )

zrevrank :: (RedisArg key, RedisArg member, RedisResult a)
    => key -- ^ 
    -> member -- ^ 
    -> Redis a
zrevrank key member = sendRequest (["ZREVRANK"] ++ [encode key] ++ [encode member] )

brpoplpush :: (RedisArg source, RedisArg destination, RedisArg timeout, RedisResult a)
    => source -- ^ 
    -> destination -- ^ 
    -> timeout -- ^ 
    -> Redis a
brpoplpush source destination timeout = sendRequest (["BRPOPLPUSH"] ++ [encode source] ++ [encode destination] ++ [encode timeout] )

incrby :: (RedisArg key, RedisArg increment, RedisResult a)
    => key -- ^ 
    -> increment -- ^ 
    -> Redis a
incrby key increment = sendRequest (["INCRBY"] ++ [encode key] ++ [encode increment] )

rpop :: (RedisArg key, RedisResult a)
    => key -- ^ 
    -> Redis a
rpop key = sendRequest (["RPOP"] ++ [encode key] )

setrange :: (RedisArg key, RedisArg offset, RedisArg value, RedisResult a)
    => key -- ^ 
    -> offset -- ^ 
    -> value -- ^ 
    -> Redis a
setrange key offset value = sendRequest (["SETRANGE"] ++ [encode key] ++ [encode offset] ++ [encode value] )

setbit :: (RedisArg key, RedisArg offset, RedisArg value, RedisResult a)
    => key -- ^ 
    -> offset -- ^ 
    -> value -- ^ 
    -> Redis a
setbit key offset value = sendRequest (["SETBIT"] ++ [encode key] ++ [encode offset] ++ [encode value] )

save :: (RedisResult a)
    => Redis a
save  = sendRequest (["SAVE"] )

echo :: (RedisArg message, RedisResult a)
    => message -- ^ 
    -> Redis a
echo message = sendRequest (["ECHO"] ++ [encode message] )

blpop :: (RedisArg key, RedisArg timeout, RedisResult a)
    => [key] -- ^ 
    -> timeout -- ^ 
    -> Redis a
blpop key timeout = sendRequest (["BLPOP"] ++ map encode key ++ [encode timeout] )

sdiffstore :: (RedisArg destination, RedisArg key, RedisResult a)
    => destination -- ^ 
    -> [key] -- ^ 
    -> Redis a
sdiffstore destination key = sendRequest (["SDIFFSTORE"] ++ [encode destination] ++ map encode key )

move :: (RedisArg key, RedisArg db, RedisResult a)
    => key -- ^ 
    -> db -- ^ 
    -> Redis a
move key db = sendRequest (["MOVE"] ++ [encode key] ++ [encode db] )

multi :: (RedisResult a)
    => Redis a
multi  = sendRequest (["MULTI"] )

getrange :: (RedisArg key, RedisArg start, RedisArg end, RedisResult a)
    => key -- ^ 
    -> start -- ^ 
    -> end -- ^ 
    -> Redis a
getrange key start end = sendRequest (["GETRANGE"] ++ [encode key] ++ [encode start] ++ [encode end] )

srem :: (RedisArg key, RedisArg member, RedisResult a)
    => key -- ^ 
    -> [member] -- ^ 
    -> Redis a
srem key member = sendRequest (["SREM"] ++ [encode key] ++ map encode member )

watch :: (RedisArg key, RedisResult a)
    => [key] -- ^ 
    -> Redis a
watch key = sendRequest (["WATCH"] ++ map encode key )

getbit :: (RedisArg key, RedisArg offset, RedisResult a)
    => key -- ^ 
    -> offset -- ^ 
    -> Redis a
getbit key offset = sendRequest (["GETBIT"] ++ [encode key] ++ [encode offset] )

zcount :: (RedisArg key, RedisArg min, RedisArg max, RedisResult a)
    => key -- ^ 
    -> min -- ^ 
    -> max -- ^ 
    -> Redis a
zcount key min max = sendRequest (["ZCOUNT"] ++ [encode key] ++ [encode min] ++ [encode max] )

quit :: (RedisResult a)
    => Redis a
quit  = sendRequest (["QUIT"] )

msetnx :: (RedisArg key, RedisArg value, RedisResult a)
    => [(key,value)] -- ^ 
    -> Redis a
msetnx keyValue = sendRequest (["MSETNX"] ++ concatMap (\(x,y) -> [encode x,encode y])keyValue )

sismember :: (RedisArg key, RedisArg member, RedisResult a)
    => key -- ^ 
    -> member -- ^ 
    -> Redis a
sismember key member = sendRequest (["SISMEMBER"] ++ [encode key] ++ [encode member] )

bgrewriteaof :: (RedisResult a)
    => Redis a
bgrewriteaof  = sendRequest (["BGREWRITEAOF"] )

hmset :: (RedisArg key, RedisArg field, RedisArg value, RedisResult a)
    => key -- ^ 
    -> [(field,value)] -- ^ 
    -> Redis a
hmset key fieldValue = sendRequest (["HMSET"] ++ [encode key] ++ concatMap (\(x,y) -> [encode x,encode y])fieldValue )

scard :: (RedisArg key, RedisResult a)
    => key -- ^ 
    -> Redis a
scard key = sendRequest (["SCARD"] ++ [encode key] )

zincrby :: (RedisArg key, RedisArg increment, RedisArg member, RedisResult a)
    => key -- ^ 
    -> increment -- ^ 
    -> member -- ^ 
    -> Redis a
zincrby key increment member = sendRequest (["ZINCRBY"] ++ [encode key] ++ [encode increment] ++ [encode member] )

sinter :: (RedisArg key, RedisResult a)
    => [key] -- ^ 
    -> Redis a
sinter key = sendRequest (["SINTER"] ++ map encode key )

mset :: (RedisArg key, RedisArg value, RedisResult a)
    => [(key,value)] -- ^ 
    -> Redis a
mset keyValue = sendRequest (["MSET"] ++ concatMap (\(x,y) -> [encode x,encode y])keyValue )

rpoplpush :: (RedisArg source, RedisArg destination, RedisResult a)
    => source -- ^ 
    -> destination -- ^ 
    -> Redis a
rpoplpush source destination = sendRequest (["RPOPLPUSH"] ++ [encode source] ++ [encode destination] )

hlen :: (RedisArg key, RedisResult a)
    => key -- ^ 
    -> Redis a
hlen key = sendRequest (["HLEN"] ++ [encode key] )

setex :: (RedisArg key, RedisArg seconds, RedisArg value, RedisResult a)
    => key -- ^ 
    -> seconds -- ^ 
    -> value -- ^ 
    -> Redis a
setex key seconds value = sendRequest (["SETEX"] ++ [encode key] ++ [encode seconds] ++ [encode value] )

sunionstore :: (RedisArg destination, RedisArg key, RedisResult a)
    => destination -- ^ 
    -> [key] -- ^ 
    -> Redis a
sunionstore destination key = sendRequest (["SUNIONSTORE"] ++ [encode destination] ++ map encode key )

brpop :: (RedisArg key, RedisArg timeout, RedisResult a)
    => [key] -- ^ 
    -> timeout -- ^ 
    -> Redis a
brpop key timeout = sendRequest (["BRPOP"] ++ map encode key ++ [encode timeout] )

hgetall :: (RedisArg key, RedisResult a)
    => key -- ^ 
    -> Redis a
hgetall key = sendRequest (["HGETALL"] ++ [encode key] )

dbsize :: (RedisResult a)
    => Redis a
dbsize  = sendRequest (["DBSIZE"] )

lpop :: (RedisArg key, RedisResult a)
    => key -- ^ 
    -> Redis a
lpop key = sendRequest (["LPOP"] ++ [encode key] )

hmget :: (RedisArg key, RedisArg field, RedisResult a)
    => key -- ^ 
    -> [field] -- ^ 
    -> Redis a
hmget key field = sendRequest (["HMGET"] ++ [encode key] ++ map encode field )

lrange :: (RedisArg key, RedisArg start, RedisArg stop, RedisResult a)
    => key -- ^ 
    -> start -- ^ 
    -> stop -- ^ 
    -> Redis a
lrange key start stop = sendRequest (["LRANGE"] ++ [encode key] ++ [encode start] ++ [encode stop] )

expire :: (RedisArg key, RedisArg seconds, RedisResult a)
    => key -- ^ 
    -> seconds -- ^ 
    -> Redis a
expire key seconds = sendRequest (["EXPIRE"] ++ [encode key] ++ [encode seconds] )

lastsave :: (RedisResult a)
    => Redis a
lastsave  = sendRequest (["LASTSAVE"] )

llen :: (RedisArg key, RedisResult a)
    => key -- ^ 
    -> Redis a
llen key = sendRequest (["LLEN"] ++ [encode key] )

decrby :: (RedisArg key, RedisArg decrement, RedisResult a)
    => key -- ^ 
    -> decrement -- ^ 
    -> Redis a
decrby key decrement = sendRequest (["DECRBY"] ++ [encode key] ++ [encode decrement] )

exec :: (RedisResult a)
    => Redis a
exec  = sendRequest (["EXEC"] )

mget :: (RedisArg key, RedisResult a)
    => [key] -- ^ 
    -> Redis a
mget key = sendRequest (["MGET"] ++ map encode key )

zadd :: (RedisArg key, RedisArg score, RedisArg member, RedisResult a)
    => key -- ^ 
    -> [(score,member)] -- ^ 
    -> Redis a
zadd key scoreMember = sendRequest (["ZADD"] ++ [encode key] ++ concatMap (\(x,y) -> [encode x,encode y])scoreMember )

keys :: (RedisArg pattern, RedisResult a)
    => pattern -- ^ 
    -> Redis a
keys pattern = sendRequest (["KEYS"] ++ [encode pattern] )

bgsave :: (RedisResult a)
    => Redis a
bgsave  = sendRequest (["BGSAVE"] )

slaveof :: (RedisArg host, RedisArg port, RedisResult a)
    => host -- ^ 
    -> port -- ^ 
    -> Redis a
slaveof host port = sendRequest (["SLAVEOF"] ++ [encode host] ++ [encode port] )

getset :: (RedisArg key, RedisArg value, RedisResult a)
    => key -- ^ 
    -> value -- ^ 
    -> Redis a
getset key value = sendRequest (["GETSET"] ++ [encode key] ++ [encode value] )

rpushx :: (RedisArg key, RedisArg value, RedisResult a)
    => key -- ^ 
    -> value -- ^ 
    -> Redis a
rpushx key value = sendRequest (["RPUSHX"] ++ [encode key] ++ [encode value] )

setnx :: (RedisArg key, RedisArg value, RedisResult a)
    => key -- ^ 
    -> value -- ^ 
    -> Redis a
setnx key value = sendRequest (["SETNX"] ++ [encode key] ++ [encode value] )

zrank :: (RedisArg key, RedisArg member, RedisResult a)
    => key -- ^ 
    -> member -- ^ 
    -> Redis a
zrank key member = sendRequest (["ZRANK"] ++ [encode key] ++ [encode member] )

zremrangebyscore :: (RedisArg key, RedisArg min, RedisArg max, RedisResult a)
    => key -- ^ 
    -> min -- ^ 
    -> max -- ^ 
    -> Redis a
zremrangebyscore key min max = sendRequest (["ZREMRANGEBYSCORE"] ++ [encode key] ++ [encode min] ++ [encode max] )

ttl :: (RedisArg key, RedisResult a)
    => key -- ^ 
    -> Redis a
ttl key = sendRequest (["TTL"] ++ [encode key] )

hkeys :: (RedisArg key, RedisResult a)
    => key -- ^ 
    -> Redis a
hkeys key = sendRequest (["HKEYS"] ++ [encode key] )

rpush :: (RedisArg key, RedisArg value, RedisResult a)
    => key -- ^ 
    -> [value] -- ^ 
    -> Redis a
rpush key value = sendRequest (["RPUSH"] ++ [encode key] ++ map encode value )

randomkey :: (RedisResult a)
    => Redis a
randomkey  = sendRequest (["RANDOMKEY"] )

spop :: (RedisArg key, RedisResult a)
    => key -- ^ 
    -> Redis a
spop key = sendRequest (["SPOP"] ++ [encode key] )

hsetnx :: (RedisArg key, RedisArg field, RedisArg value, RedisResult a)
    => key -- ^ 
    -> field -- ^ 
    -> value -- ^ 
    -> Redis a
hsetnx key field value = sendRequest (["HSETNX"] ++ [encode key] ++ [encode field] ++ [encode value] )

configGet :: (RedisArg parameter, RedisResult a)
    => parameter -- ^ 
    -> Redis a
configGet parameter = sendRequest (["CONFIG","GET"] ++ [encode parameter] )

hvals :: (RedisArg key, RedisResult a)
    => key -- ^ 
    -> Redis a
hvals key = sendRequest (["HVALS"] ++ [encode key] )

exists :: (RedisArg key, RedisResult a)
    => key -- ^ 
    -> Redis a
exists key = sendRequest (["EXISTS"] ++ [encode key] )

sunion :: (RedisArg key, RedisResult a)
    => [key] -- ^ 
    -> Redis a
sunion key = sendRequest (["SUNION"] ++ map encode key )

zrem :: (RedisArg key, RedisArg member, RedisResult a)
    => key -- ^ 
    -> [member] -- ^ 
    -> Redis a
zrem key member = sendRequest (["ZREM"] ++ [encode key] ++ map encode member )

smembers :: (RedisArg key, RedisResult a)
    => key -- ^ 
    -> Redis a
smembers key = sendRequest (["SMEMBERS"] ++ [encode key] )

ping :: (RedisResult a)
    => Redis a
ping  = sendRequest (["PING"] )

rename :: (RedisArg key, RedisArg newkey, RedisResult a)
    => key -- ^ 
    -> newkey -- ^ 
    -> Redis a
rename key newkey = sendRequest (["RENAME"] ++ [encode key] ++ [encode newkey] )

decr :: (RedisArg key, RedisResult a)
    => key -- ^ 
    -> Redis a
decr key = sendRequest (["DECR"] ++ [encode key] )

select :: (RedisArg index, RedisResult a)
    => index -- ^ 
    -> Redis a
select index = sendRequest (["SELECT"] ++ [encode index] )

hexists :: (RedisArg key, RedisArg field, RedisResult a)
    => key -- ^ 
    -> field -- ^ 
    -> Redis a
hexists key field = sendRequest (["HEXISTS"] ++ [encode key] ++ [encode field] )

auth :: (RedisArg password, RedisResult a)
    => password -- ^ 
    -> Redis a
auth password = sendRequest (["AUTH"] ++ [encode password] )

sinterstore :: (RedisArg destination, RedisArg key, RedisResult a)
    => destination -- ^ 
    -> [key] -- ^ 
    -> Redis a
sinterstore destination key = sendRequest (["SINTERSTORE"] ++ [encode destination] ++ map encode key )

shutdown :: (RedisResult a)
    => Redis a
shutdown  = sendRequest (["SHUTDOWN"] )

configSet :: (RedisArg parameter, RedisArg value, RedisResult a)
    => parameter -- ^ 
    -> value -- ^ 
    -> Redis a
configSet parameter value = sendRequest (["CONFIG","SET"] ++ [encode parameter] ++ [encode value] )

renamenx :: (RedisArg key, RedisArg newkey, RedisResult a)
    => key -- ^ 
    -> newkey -- ^ 
    -> Redis a
renamenx key newkey = sendRequest (["RENAMENX"] ++ [encode key] ++ [encode newkey] )

expireat :: (RedisArg key, RedisArg timestamp, RedisResult a)
    => key -- ^ 
    -> timestamp -- ^ 
    -> Redis a
expireat key timestamp = sendRequest (["EXPIREAT"] ++ [encode key] ++ [encode timestamp] )

get :: (RedisArg key, RedisResult a)
    => key -- ^ 
    -> Redis a
get key = sendRequest (["GET"] ++ [encode key] )

lrem :: (RedisArg key, RedisArg count, RedisArg value, RedisResult a)
    => key -- ^ 
    -> count -- ^ 
    -> value -- ^ 
    -> Redis a
lrem key count value = sendRequest (["LREM"] ++ [encode key] ++ [encode count] ++ [encode value] )

incr :: (RedisArg key, RedisResult a)
    => key -- ^ 
    -> Redis a
incr key = sendRequest (["INCR"] ++ [encode key] )

zcard :: (RedisArg key, RedisResult a)
    => key -- ^ 
    -> Redis a
zcard key = sendRequest (["ZCARD"] ++ [encode key] )

ltrim :: (RedisArg key, RedisArg start, RedisArg stop, RedisResult a)
    => key -- ^ 
    -> start -- ^ 
    -> stop -- ^ 
    -> Redis a
ltrim key start stop = sendRequest (["LTRIM"] ++ [encode key] ++ [encode start] ++ [encode stop] )

append :: (RedisArg key, RedisArg value, RedisResult a)
    => key -- ^ 
    -> value -- ^ 
    -> Redis a
append key value = sendRequest (["APPEND"] ++ [encode key] ++ [encode value] )

lset :: (RedisArg key, RedisArg index, RedisArg value, RedisResult a)
    => key -- ^ 
    -> index -- ^ 
    -> value -- ^ 
    -> Redis a
lset key index value = sendRequest (["LSET"] ++ [encode key] ++ [encode index] ++ [encode value] )

info :: (RedisResult a)
    => Redis a
info  = sendRequest (["INFO"] )

hget :: (RedisArg key, RedisArg field, RedisResult a)
    => key -- ^ 
    -> field -- ^ 
    -> Redis a
hget key field = sendRequest (["HGET"] ++ [encode key] ++ [encode field] )

sdiff :: (RedisArg key, RedisResult a)
    => [key] -- ^ 
    -> Redis a
sdiff key = sendRequest (["SDIFF"] ++ map encode key )

smove :: (RedisArg source, RedisArg destination, RedisArg member, RedisResult a)
    => source -- ^ 
    -> destination -- ^ 
    -> member -- ^ 
    -> Redis a
smove source destination member = sendRequest (["SMOVE"] ++ [encode source] ++ [encode destination] ++ [encode member] )

flushdb :: (RedisResult a)
    => Redis a
flushdb  = sendRequest (["FLUSHDB"] )

set :: (RedisArg key, RedisArg value, RedisResult a)
    => key -- ^ 
    -> value -- ^ 
    -> Redis a
set key value = sendRequest (["SET"] ++ [encode key] ++ [encode value] )

zremrangebyrank :: (RedisArg key, RedisArg start, RedisArg stop, RedisResult a)
    => key -- ^ 
    -> start -- ^ 
    -> stop -- ^ 
    -> Redis a
zremrangebyrank key start stop = sendRequest (["ZREMRANGEBYRANK"] ++ [encode key] ++ [encode start] ++ [encode stop] )

sadd :: (RedisArg key, RedisArg member, RedisResult a)
    => key -- ^ 
    -> [member] -- ^ 
    -> Redis a
sadd key member = sendRequest (["SADD"] ++ [encode key] ++ map encode member )

lpush :: (RedisArg key, RedisArg value, RedisResult a)
    => key -- ^ 
    -> [value] -- ^ 
    -> Redis a
lpush key value = sendRequest (["LPUSH"] ++ [encode key] ++ map encode value )

lindex :: (RedisArg key, RedisArg index, RedisResult a)
    => key -- ^ 
    -> index -- ^ 
    -> Redis a
lindex key index = sendRequest (["LINDEX"] ++ [encode key] ++ [encode index] )

zscore :: (RedisArg key, RedisArg member, RedisResult a)
    => key -- ^ 
    -> member -- ^ 
    -> Redis a
zscore key member = sendRequest (["ZSCORE"] ++ [encode key] ++ [encode member] )

strlen :: (RedisArg key, RedisResult a)
    => key -- ^ 
    -> Redis a
strlen key = sendRequest (["STRLEN"] ++ [encode key] )

unwatch :: (RedisResult a)
    => Redis a
unwatch  = sendRequest (["UNWATCH"] )

hset :: (RedisArg key, RedisArg field, RedisArg value, RedisResult a)
    => key -- ^ 
    -> field -- ^ 
    -> value -- ^ 
    -> Redis a
hset key field value = sendRequest (["HSET"] ++ [encode key] ++ [encode field] ++ [encode value] )

lpushx :: (RedisArg key, RedisArg value, RedisResult a)
    => key -- ^ 
    -> value -- ^ 
    -> Redis a
lpushx key value = sendRequest (["LPUSHX"] ++ [encode key] ++ [encode value] )

discard :: (RedisResult a)
    => Redis a
discard  = sendRequest (["DISCARD"] )

srandmember :: (RedisArg key, RedisResult a)
    => key -- ^ 
    -> Redis a
srandmember key = sendRequest (["SRANDMEMBER"] ++ [encode key] )

persist :: (RedisArg key, RedisResult a)
    => key -- ^ 
    -> Redis a
persist key = sendRequest (["PERSIST"] ++ [encode key] )


